### ISSUE TITLE
[FEATURE] Create chuncked filters in adapta

### ISSUE THREAD

**Issue by lucasgml** [SneaksAndData/adapta#368]
Right now we have to write _reduce_filter_expression function every time we fetch prices from Astra tables. This function would help to avoid (1) duplicated code in different projects and (2) reach max recursion depth due to the amount of filters

    product_locs = chunk_list(product_locations.to_dict(orient="records"), 100)

    def _reduce_filter_expression(row_filters: List[Dict[str, Union[str, int, float]]]) -> Expression:
        return reduce(
            lambda x, y: x | y,
            [
                (
                    (FilterField(ASTRA_PRICE_SCHEMA.location_key) == row[ASTRA_PRICE_SCHEMA.location_key])
                    & (FilterField(ASTRA_PRICE_SCHEMA.product_number) == row[ASTRA_PRICE_SCHEMA.product_number])
                    & (FilterField(ASTRA_PRICE_SCHEMA.sink_country_code) == row[ASTRA_PRICE_SCHEMA.sink_country_code])
                    & (FilterField(ASTRA_PRICE_SCHEMA.sku_quality) == row[ASTRA_PRICE_SCHEMA.sku_quality])
                )
                for row in row_filters
            ],
        )

    filters = reduce(lambda x, y: x | y, [_reduce_filter_expression(product_loc) for product_loc in product_locs])

**Comment by henrikfoss** [comment]
`Failed to solve request. - (request_id:ad30d5eb-5505-444b-8e3b-4f93fc1fe6ed), (country_code:US), (order_type:Online order - home delivery)
Traceback (most recent call last):
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/main.py", line 118, in main
    oc_solution, input_dfs, optimization_data = run_optimization_process(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/optimization_process.py", line 99, in run_optimization_process
    extended_input, data = fetch_data(
                           ^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/data_processing/pre_processing.py", line 283, in fetch_data
    data = runner.eager()
           ^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/utils/concurrent_task_runner.py", line 109, in eager
    return {task_name: task.result() for task_name, task in self._run_tasks().items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/utils/concurrent_task_runner.py", line 109, in <dictcomp>
    return {task_name: task.result() for task_name, task in self._run_tasks().items()}
                       ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/data_processing/fetch_functions/fetch_demand.py", line 117, in fetch_demand
    result = client.filter_entities(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/distributed_object_store/datastax_astra/astra_client.py", line 302, in filter_entities
    compile_expression(key_column_filter_values, AstraFilterExpression)
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 262, in compile_expression
    return target().compile(expr)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 989 more times]
RecursionError: maximum recursion depth exceeded

Process finished with exit code 1
`

**Comment by henrikfoss** [comment]
Here is an example if the filter is too big and chunking is not performed:

`
Failed to solve request. - (request_id:ad30d5eb-5505-444b-8e3b-4f93fc1fe6ed), (country_code:US), (order_type:Online order - home delivery)
Traceback (most recent call last):
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/main.py", line 118, in main
    oc_solution, input_dfs, optimization_data = run_optimization_process(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/optimization_process.py", line 99, in run_optimization_process
    extended_input, data = fetch_data(
                           ^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/data_processing/pre_processing.py", line 283, in fetch_data
    data = runner.eager()
           ^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/utils/concurrent_task_runner.py", line 109, in eager
    return {task_name: task.result() for task_name, task in self._run_tasks().items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/utils/concurrent_task_runner.py", line 109, in <dictcomp>
    return {task_name: task.result() for task_name, task in self._run_tasks().items()}
                       ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/PycharmProjects/omni-channel-crystal-solver/ecco_omni_channel_crystal_solver/data_processing/fetch_functions/fetch_demand.py", line 117, in fetch_demand
    result = client.filter_entities(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/distributed_object_store/datastax_astra/astra_client.py", line 302, in filter_entities
    compile_expression(key_column_filter_values, AstraFilterExpression)
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 262, in compile_expression
    return target().compile(expr)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hfj/.cache/pypoetry/virtualenvs/omni-channel-crystal-solver-BUzSMOZ0-py3.11/lib/python3.11/site-packages/adapta/storage/models/filter_expression.py", line 193, in compile
    left_compiled = self.compile(expr.left_operand)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 989 more times]
RecursionError: maximum recursion depth exceeded

Process finished with exit code 1

`
